#!/bin/bash
#PBS -N demo_asbs
#PBS -P gs_ccds_haidang.dau
#PBS -q gpu_as
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=12:ngpus=3
#PBS -j oe

cd "$PBS_O_WORKDIR"

module load anaconda/2025
eval "$(/usr/local/anaconda2025/bin/conda shell.bash hook)"
conda activate BMS

IFS=',' read -r -a GPUS <<< "$CUDA_VISIBLE_DEVICES"

for s in 0 1 2; do
  CUDA_VISIBLE_DEVICES="${GPUS[$s]}" python train.py \
    experiment=demo_asbs \
    seed=${s} \
    exp_name=demo_asbs_seed${s} \
    hydra.run.dir=results/demo_asbs/seed${s} &
done

wait